import { MfeProps } from "types/digi-props";
import {
  AssetType,
  ChannelId,
  ChannelSite,
  Locale,
  RegionId,
  ServiceFlag,
} from "types/enums";

export const providerProps: MfeProps = {
  authGWCode: "",
  sysGenUid: "123456",
  sysGenUID: "123456",
  apiDomainUrl: "http://localhost:9189/",
  portfolioNo: "",
  serviceFlag: ServiceFlag.TRADING,
  region: RegionId.TW,
  channel: ChannelSite.MB,
  encryptedPortfolios: { a: "123" },
  clientSegment: "",
  deviceInfo: {
    appVersion: "7.11.5",
    clientId: "1234567",
    locale: Locale.ZH,
    osType: "Android",
    osVersion: "10",
  },
  exchangeCountry: "US",
  assetsCode: "",
  landingPage: "",
  channelId: ChannelId.MBTW,
  regionId: RegionId.TW,
  language: Locale.EN,
  longitude: "",
  latitude: "",
  sessionId: "",
  clientIpAddress: "",
  baseAppActions: {
    sessionExpired: undefined,
    hideHeader: undefined,
  },
  features: [{ featureId: "", url: "", enabled: false, strategy: null }],
  selectedPortfolio: {
    id: "123",
    displayNumber: "S-801135-0",
    isCryptoEnabled: true,
    reportingCurrency: "CAD",
  },
  apiCommonHeader: {
    "user-id": "S-801135-0",
    sessionId: "123456",
    "cust-sysgen-id": "123456",
    channelId: ChannelId.MBTW,
    longitude: "",
    latitude: "",
    language: "en-TW",
    regionId: RegionId.TW,
    clientId: "1234567",
    Authorization: "token",
    "Content-Type": "application/json",
    Accept: "application/json",
    assetType: AssetType.EQUITY,
  },
  portfolioAccounts: {
    portfolioNo: "",
    accounts: [],
    fetching: true,
    error: 0,
    selectedPortfolio: {
      id: "123",
      displayNumber: "S-801135-0",
      isCryptoEnabled: true,
      reportingCurrency: "CAD",
    },
    hasCryptoTradingAccount: true,
    hasOETAccount: true,
  },
  apiServer: "",
};
